#! /bin/bash
# General system info, memory, load etc.

echo "******************** General system status ********************"
mem=$(free -m | grep "Mem" | awk '{print $3,"/",$2," MB (FREE:",$4,"MB)"}')
swap=$(free -m | grep "Swap" | awk '{print $3,"/",$2}')
load=$(uptime | awk '{print $10, $11, $12}')
uptime=$(uptime | awk '{print $3, $4}' | tr -d ",")

echo Uptime: $uptime
echo System load: $load
echo Memory: $mem
echo Swap: $swap
