#! /bin/bash
# Prints megaraid status

# If sas is used, change this to true
SAS=false

if $SAS; then
    MEGARAID="/usr/sbin/megaraidsas-status"
else
    MEGARAID="/usr/sbin/megaraid-status"
fi

echo "******************** Megaraid arrays ********************"

if ! $(command -v $MEGARAID &> /dev/null); then
    echo "megaraid-status or megaraidsas-status not installed"
    exit 1
fi

if [[ `$MEGARAID | grep "RAID" | grep -o "optimal"` != "optimal" ]]; then
    echo "<font color='red'>ALERT: RAID STATUS NOT OPTIMAL!</font>"
fi
$MEGARAID
