#! /bin/bash
# Check smartdata of disks on system

if (($UID != 0)); then
    echo "*!* FATAL: RUN AS ROOT"
    exit 1
fi

if ! $(hash smartctl &> /dev/null); then
    echo "smart-tools not installed"
    exit 1
fi

ddtemp="/tmp/smartdata_$$"
touch $ddtemp

if [ -f $ddtemp ]; then
	ls -1 /dev | grep sd | cut -c 1-3 | uniq > $ddtemp
fi

echo "******************** Disk S.M.A.R.T data ********************"

while read DISK; do
    temp=$(smartctl -A /dev/$DISK | grep -i temperature | awk '{print $10}')
    smart=$(smartctl -a /dev/$DISK | grep "SMART overall-health self-assessment test result:" | cut -c 51-56)
    age=$(smartctl -A /dev/$DISK | grep Power_On_Hours | awk '{print $10}')
    loadcount=$(smartctl -A /dev/$DISK | grep "Load_Cycle_Count" | awk '{print $10}')
    size=$(smartctl -i /dev/$DISK | grep "Capacity" | awk '{print $3}' | sed 's/,//g')
    let size=$size/1000000000
    let ctemp=$temp
    let age=($age)/24
    let lcc=$loadcount

    output=""
    typeset -u UCDISK=$DISK

    output+="$UCDISK: $temp°C, "
    output+="S.M.A.R.T: $smart, "

    if (( $age > 365 )); then
        age=$(echo "scale=2; $age"/365 | bc)
        output+="age: $age years. "
    else
        output+="age: $age days. "
    fi
    output+="Load count: $loadcount, "
    output+="Size: $size GB"
    echo -e $output

done < $ddtemp
rm $ddtemp
