#! /bin/bash
# Shows current ufw status

if (($UID != 0)); then
    echo "*!* FATAL: RUN AS ROOT"
    exit 1
fi

if ! $(hash ufw &> /dev/null); then
    echo "ufw not installed"
    exit 1
else
    echo "******************** Ufw firewall ********************"
    status=$(ufw status | head -n 1)
    if [[ "$status" == *inactive* ]]; then
        echo "ufw is not enabled"
    else
        ufw status verbose
    fi
fi
