#! /bin/bash
# Shows current ufw status

if (($UID != 0)); then
    echo "*!* FATAL: RUN AS ROOT"
    exit 1
fi

UFW="/usr/sbin/ufw"

if ! $(command -v $UFW &> /dev/null); then
    echo "ufw not installed"
    exit 1
fi

echo "******************** Ufw firewall ********************"

status=$($UFW status | head -n 1)
if [[ "$status" == *inactive* ]]; then
    echo "ufw is not enabled"
else
    $UFW status verbose
fi
